# ==============================================================================
# FILE: recipes/optuna_64.yaml
# Hyperparameter Optimization for 64x64 Resolution (MiniCNN + ResNet-18)
# ==============================================================================
# Usage: orchard run recipes/optuna_64.yaml
# Estimated Time: ~15-30 min GPU (20 trials × 10 epochs, RTX 5070)
# Memory Usage: ~1-2GB VRAM per trial
#
# OPTUNA SEARCH SPACE:
#   Model pool: mini_cnn, resnet_18 (automatic architecture selection)
#   See optuna_mini_cnn.yaml header for full search space documentation.

dataset:
  name: "bloodmnist"
  data_root: ./dataset
  resolution: 64
  force_rgb: true
  use_weighted_sampler: true
  max_samples: null

architecture:
  name: "mini_cnn"              # Will be optimized vs resnet_18
  pretrained: false
  weight_variant: null
  dropout: 0.3

training:
  seed: 42

  batch_size: 64
  learning_rate: 0.01
  weight_decay: 5e-4
  momentum: 0.9
  min_lr: 1e-6

  mixup_alpha: 0.0
  label_smoothing: 0.0

  epochs: 60
  patience: 15
  grad_clip: 1.0
  mixup_epochs: 60              # Capped to optuna.epochs by config_builder

  monitor_metric: "auc"
  scheduler_type: "cosine"
  scheduler_patience: 5
  scheduler_factor: 0.1
  step_size: 20

  use_amp: false
  use_tta: false
  criterion_type: "cross_entropy"
  weighted_loss: false
  focal_gamma: 2.0

augmentation:
  hflip: 0.5
  rotation_angle: 10
  jitter_val: 0.2
  min_scale: 0.9
  tta_translate: 0.5
  tta_scale: 1.02
  tta_blur_sigma: 0.1
  tta_blur_kernel_size: 3

hardware:
  device: "auto"
  reproducible: false

telemetry:
  output_dir: ./outputs
  log_level: "INFO"
  log_interval: 50

evaluation:
  n_samples: 16
  fig_dpi: 200
  cmap_confusion: Blues
  plot_style: seaborn-v0_8-muted
  grid_cols: 4
  fig_size_predictions: [12, 8]
  report_format: xlsx
  save_confusion_matrix: true
  save_predictions_grid: true

optuna:
  study_name: "bloodmnist_64_model_search"
  n_trials: 20
  epochs: 10
  timeout: null

  metric_name: "accuracy"
  direction: "maximize"

  enable_early_stopping: true
  early_stopping_threshold: 0.999
  early_stopping_patience: 3

  sampler_type: "tpe"
  search_space_preset: "full"
  enable_model_search: true
  model_pool: ["mini_cnn", "resnet_18"]

  enable_pruning: true
  pruner_type: "median"
  pruning_warmup_epochs: 3

  storage_type: "sqlite"
  storage_path: null

  n_jobs: 1
  load_if_exists: true
  show_progress_bar: false

  save_plots: true
  save_best_config: true

  search_space_overrides:
      learning_rate:
          low: 1.0e-05
          high: 0.01
          log: true
      weight_decay:
          low: 1.0e-06
          high: 0.001
          log: true
      momentum:
          low: 0.85
          high: 0.95
          log: false
      min_lr:
          low: 1.0e-07
          high: 1.0e-05
          log: true
      mixup_alpha:
          low: 0.0
          high: 0.4
          log: false
      label_smoothing:
          low: 0.0
          high: 0.2
          log: false
      dropout:
          low: 0.1
          high: 0.5
          log: false
      scheduler_patience:
          low: 3
          high: 10
      rotation_angle:
          low: 0
          high: 15
      jitter_val:
          low: 0.0
          high: 0.15
          log: false
      min_scale:
          low: 0.9
          high: 1.0
          log: false
      batch_size_low_res:
      - 16
      - 32
      - 48
      - 64
      batch_size_high_res:
      - 8
      - 12
      - 16

tracking:
  enabled: true
  experiment_name: "orchard-ml"

export:
  format: onnx
  opset_version: 18
  validate_export: true
