# ==============================================================================
# FILE: recipes/optuna_cifar100_mini_cnn.yaml
# MiniCNN on CIFAR-100 (32x32) with Optuna Optimization
# ==============================================================================
# Usage: orchard run recipes/optuna_cifar100_mini_cnn.yaml
# Estimated Time: ~1-2h GPU (50 trials × 10 epochs, RTX 5070)
# Memory Usage: ~1GB VRAM per trial
#
# ARCHITECTURE SEARCH:
#   This recipe uses model_pool to compare lightweight architectures
#   suited for 32×32 input. All models train from scratch (pretrained: false)
#   to avoid ImageNet semantic overlap with CIFAR categories.
#
#   Pool:
#     - mini_cnn           : Built-in 3-conv CNN (~95K params, fast baseline)
#     - resnet_18           : Built-in ResNet-18 with small stem (~11M params)
#     - timm/mobilenetv3_small_100 : MobileNetV3-Small (~1.5M params, efficient)
#     - timm/efficientnet_lite0    : EfficientNet-Lite0 (~4.7M, mobile-optimized)

dataset:
  name: "cifar100"
  resolution: 32
  force_rgb: true
  use_weighted_sampler: true

architecture:
  name: "mini_cnn"
  pretrained: false
  dropout: 0.3

training:
  seed: 42
  batch_size: 128
  learning_rate: 0.01
  weight_decay: 5e-4
  momentum: 0.9
  min_lr: 1e-6
  mixup_alpha: 0.0
  label_smoothing: 0.0
  epochs: 60
  patience: 15
  grad_clip: 1.0
  mixup_epochs: 0
  monitor_metric: "auc"
  scheduler_type: "cosine"
  scheduler_patience: 5
  scheduler_factor: 0.1
  step_size: 20
  use_amp: false
  use_tta: false
  criterion_type: "cross_entropy"
  weighted_loss: false
  focal_gamma: 2.0

augmentation:
  hflip: 0.5
  rotation_angle: 10
  jitter_val: 0.2
  min_scale: 0.9
  tta_translate: 0.5
  tta_scale: 1.02
  tta_blur_sigma: 0.1

hardware:
  device: "auto"
  reproducible: false

telemetry:
  output_dir: ./outputs
  log_level: "INFO"
  log_interval: 50

evaluation:
  n_samples: 16
  fig_dpi: 200
  cmap_confusion: Blues
  plot_style: seaborn-v0_8-muted
  grid_cols: 4
  fig_size_predictions: [12, 8]
  report_format: xlsx
  save_confusion_matrix: true
  save_predictions_grid: true

optuna:
  study_name: "cifar100_minicnn_optimized"
  n_trials: 50
  epochs: 10
  timeout: null
  metric_name: "auc"
  direction: "maximize"
  enable_early_stopping: true
  early_stopping_threshold: 0.999
  early_stopping_patience: 3
  sampler_type: "tpe"
  search_space_preset: "full"
  enable_model_search: true
  # Lightweight architectures for 32×32 — from scratch, no ImageNet bias
  model_pool:
    - "mini_cnn"
    - "resnet_18"
    - "timm/mobilenetv3_small_100"
    - "timm/efficientnet_lite0"
  enable_pruning: true
  pruner_type: "median"
  pruning_warmup_epochs: 3
  storage_type: "sqlite"
  storage_path: null
  n_jobs: 1
  load_if_exists: true
  show_progress_bar: false
  save_plots: true
  save_best_config: true

  search_space_overrides:
      learning_rate:
          low: 1.0e-05
          high: 0.01
          log: true
      weight_decay:
          low: 1.0e-06
          high: 0.001
          log: true
      momentum:
          low: 0.85
          high: 0.95
          log: false
      min_lr:
          low: 1.0e-07
          high: 1.0e-05
          log: true
      mixup_alpha:
          low: 0.0
          high: 0.4
          log: false
      label_smoothing:
          low: 0.0
          high: 0.2
          log: false
      dropout:
          low: 0.1
          high: 0.5
          log: false
      scheduler_patience:
          low: 3
          high: 10
      rotation_angle:
          low: 0
          high: 15
      jitter_val:
          low: 0.0
          high: 0.15
          log: false
      min_scale:
          low: 0.9
          high: 1.0
          log: false
      batch_size_low_res:
      - 16
      - 32
      - 48
      - 64
      batch_size_high_res:
      - 8
      - 12
      - 16

tracking:
  enabled: true
  experiment_name: "orchard-ml"

export:
  format: onnx
  opset_version: 18
  validate_export: true
